
package projectoodi;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

public class ProductFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProductFrame.class.getName());
    
    private void loadProductData() {
        try {

            javax.swing.table.DefaultTableModel model =
                    (javax.swing.table.DefaultTableModel)
                    tblProduct.getModel();
                    

            model.setRowCount(0);

            java.io.BufferedReader reader =
                    new java.io.BufferedReader(
                            new java.io.FileReader(
                                    "product.txt"));

            String line;

            while ((line = reader.readLine()) != null) {

                String[] data = line.split(",");

                model.addRow(data);
            }

            reader.close();

        } catch (Exception e) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    e.getMessage());
        }
    }
    
    private void loadViewData() {

        try {

            DefaultTableModel model =
                    (DefaultTableModel) tblView.getModel();

            model.setRowCount(0);

            java.io.BufferedReader reader =
                    new java.io.BufferedReader(
                            new java.io.FileReader("product.txt"));

            String line;

            while ((line = reader.readLine()) != null) {

            String[] data = line.split(",");

            model.addRow(new Object[]{
                data[0], 
                data[1], 
                data[2],
                data[3],

            });
        }
            reader.close();

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this,
                    e.getMessage());
        }
    }

    
    private void saveTableToFile() {
        try {

        DefaultTableModel model =
                (DefaultTableModel) tblProduct.getModel();

        java.io.BufferedWriter writer =
                new java.io.BufferedWriter(
                        new java.io.FileWriter("product.txt"));

        for (int i = 0; i < model.getRowCount(); i++) {

            writer.write(
                    model.getValueAt(i, 0).toString() + "," +
                    model.getValueAt(i, 1).toString() + "," +
                    model.getValueAt(i, 2).toString() + "," +
                    model.getValueAt(i, 3).toString());

            writer.newLine();
        }

        writer.close();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,
                e.getMessage());
    }
}
    
    private void clearFields() {
        txtproductId.setText("");
        txtproductName.setText("");
        txtproductQty.setText("");
        txtproductId1.setText("");
        txtproductName1.setText("");
        txtproductQty1.setText("");
        txtprice1.setText("");
        txtprice.setText("");

    }

    public ProductFrame() {
        initComponents();
        
        loadDeleteProduct();
        loadViewData();
        loadProductData();
        
    pnlRegister.setVisible(true);
    pnlUpdate.setVisible(false);
    pnlView.setVisible(false);
    pnlRemove.setVisible(false);


}
    private void loadDeleteProduct() {
            
            try {

                DefaultTableModel model =
                        (DefaultTableModel) tblRemove.getModel();

                model.setRowCount(0);

                BufferedReader reader =
                        new BufferedReader(
                                new FileReader("product.txt"));

                String line;

                while ((line = reader.readLine()) != null) {

                    String[] data = line.split(",");

                    if(data.length >= 4) {
                        model.addRow(data);
                    }
                }

                reader.close();

            } catch (Exception e) {

                JOptionPane.showMessageDialog(this,
                        e.getMessage());
            }
        }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        menu = new javax.swing.JLabel();
        register = new javax.swing.JButton();
        update = new javax.swing.JButton();
        view = new javax.swing.JButton();
        remove = new javax.swing.JButton();
        back = new javax.swing.JButton();
        pnlContent = new javax.swing.JPanel();
        pnlRegister = new javax.swing.JPanel();
        lblFormtitle = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtproductName = new javax.swing.JTextField();
        txtproductQty = new javax.swing.JTextField();
        txtproductId = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        pnlUpdate = new javax.swing.JPanel();
        lblFormtitle1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtproductName1 = new javax.swing.JTextField();
        txtproductQty1 = new javax.swing.JTextField();
        txtproductId1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();
        updateBtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtprice1 = new javax.swing.JTextField();
        pnlView = new javax.swing.JPanel();
        lblFormtitle2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblView = new javax.swing.JTable();
        pnlRemove = new javax.swing.JPanel();
        lblFormtitle4 = new javax.swing.JLabel();
        deleteProductBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblRemove = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setToolTipText("PRODUCT MANAGEMENT");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("PRODUCT MANAGEMENT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        menu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menu.setText("MENU");

        register.setText("Register Product");
        register.addActionListener(this::registerActionPerformed);

        update.setText("Update Product");
        update.addActionListener(this::updateActionPerformed);

        view.setText("View Product");
        view.addActionListener(this::viewActionPerformed);

        remove.setText("Remove Product");
        remove.addActionListener(this::removeActionPerformed);

        back.setText("BACK");
        back.addActionListener(this::backActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(register, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(menu)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(view, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(remove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(back)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(register)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(update)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(view)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(remove)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(back)
                .addContainerGap())
        );

        pnlContent.setLayout(new java.awt.CardLayout());

        lblFormtitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFormtitle.setText("REGISTER PRODUCT");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("PRODUCT NAME   :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("PRODUCT ID          :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("PRODUCT QTY      :");

        txtproductName.addActionListener(this::txtproductNameActionPerformed);

        txtproductId.addActionListener(this::txtproductIdActionPerformed);

        save.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        save.setText("SAVE");
        save.addActionListener(this::saveActionPerformed);

        clear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        clear.setText("CLEAR");
        clear.addActionListener(this::clearActionPerformed);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText(" PRICE PER QTY     :");

        javax.swing.GroupLayout pnlRegisterLayout = new javax.swing.GroupLayout(pnlRegister);
        pnlRegister.setLayout(pnlRegisterLayout);
        pnlRegisterLayout.setHorizontalGroup(
            pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegisterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFormtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168))
            .addGroup(pnlRegisterLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnlRegisterLayout.createSequentialGroup()
                            .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlRegisterLayout.createSequentialGroup()
                            .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel10))
                            .addGap(33, 33, 33)
                            .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtproductName, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtproductId, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtproductQty, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        pnlRegisterLayout.setVerticalGroup(
            pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegisterLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblFormtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtproductId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtproductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtproductQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        pnlContent.add(pnlRegister, "cardRegister");

        lblFormtitle1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFormtitle1.setText("UPDATE PRODUCT");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("PRICE PER QTY     : ");

        txtproductId1.addActionListener(this::txtproductId1ActionPerformed);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("PRODUCT NAME  :");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("PRODUCT ID         :");

        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NAME", "QUANTITY", "PRICE PER QTY"
            }
        ));
        tblProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProduct);

        updateBtn.setText("UPDATE");
        updateBtn.addActionListener(this::updateBtnActionPerformed);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("PRODUCT QTY     :");

        javax.swing.GroupLayout pnlUpdateLayout = new javax.swing.GroupLayout(pnlUpdate);
        pnlUpdate.setLayout(pnlUpdateLayout);
        pnlUpdateLayout.setHorizontalGroup(
            pnlUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUpdateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFormtitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154))
            .addGroup(pnlUpdateLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pnlUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateBtn)
                    .addGroup(pnlUpdateLayout.createSequentialGroup()
                        .addGroup(pnlUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel7))
                        .addGap(29, 29, 29)
                        .addGroup(pnlUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtproductName1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtproductId1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtprice1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtproductQty1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)))
                        .addGap(5, 5, 5)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        pnlUpdateLayout.setVerticalGroup(
            pnlUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUpdateLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblFormtitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtproductId1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(pnlUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtproductName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtproductQty1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(pnlUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtprice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateBtn)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pnlContent.add(pnlUpdate, "cardUpdate");

        lblFormtitle2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFormtitle2.setText("VIEW PRODUCT");

        tblView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NAME", "QUANTITY", "PRICE PER QTY"
            }
        ));
        jScrollPane2.setViewportView(tblView);

        javax.swing.GroupLayout pnlViewLayout = new javax.swing.GroupLayout(pnlView);
        pnlView.setLayout(pnlViewLayout);
        pnlViewLayout.setHorizontalGroup(
            pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViewLayout.createSequentialGroup()
                .addGroup(pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlViewLayout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(lblFormtitle2))
                    .addGroup(pnlViewLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        pnlViewLayout.setVerticalGroup(
            pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViewLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblFormtitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pnlContent.add(pnlView, "cardSearch");

        lblFormtitle4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFormtitle4.setText("DELETE PRODUCT");

        deleteProductBtn.setText("DELETE");
        deleteProductBtn.addActionListener(this::deleteProductBtnActionPerformed);

        tblRemove.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NAME", "QUANTITY", "PRICE PER QTY"
            }
        ));
        tblRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRemoveMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblRemove);

        javax.swing.GroupLayout pnlRemoveLayout = new javax.swing.GroupLayout(pnlRemove);
        pnlRemove.setLayout(pnlRemoveLayout);
        pnlRemoveLayout.setHorizontalGroup(
            pnlRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRemoveLayout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(lblFormtitle4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRemoveLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(pnlRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteProductBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
        pnlRemoveLayout.setVerticalGroup(
            pnlRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRemoveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFormtitle4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(deleteProductBtn)
                .addContainerGap())
        );

        pnlContent.add(pnlRemove, "cardRemove");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        pnlRegister.setVisible(true);
        pnlUpdate.setVisible(false);
        pnlView.setVisible(false);
        pnlRemove.setVisible(false);
       // TODO add your handling code here:
    }//GEN-LAST:event_registerActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        pnlRegister.setVisible(false);
        pnlUpdate.setVisible(true);
        pnlView.setVisible(false);
        pnlRemove.setVisible(false); 
        loadProductData();
        // TODO add your handling code here:
    }//GEN-LAST:event_updateActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        Dashboard dashboard = new Dashboard();
        dashboard.setVisible(true);

        this.dispose();
                                      
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        try {
            String productId = txtproductId.getText().trim();
            String productName = txtproductName.getText().trim();
            String productQty = txtproductQty.getText().trim();
            String productPrice = txtprice.getText().trim();

            if (productId.isEmpty() || productName.isEmpty() || productQty.isEmpty() || productPrice.isEmpty()) {        
                throw new Exception("Please fill all fields!");
            }

            java.sql.Connection conn = DBConnection.getConnection();
        if (conn != null) {
            // Arahan SQL untuk masukkan data ke table products
            String sql = "INSERT INTO products (product_id, product_name, quantity, price_unit) VALUES (?, ?, ?, ?)";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            
            pst.setString(1, productId);
            pst.setString(2, productName);
            pst.setInt(3, Integer.parseInt(productQty));
            pst.setDouble(4, Double.parseDouble(productPrice));

            int rowsInserted = pst.executeUpdate();
            if (rowsInserted > 0) {
                JOptionPane.showMessageDialog(this, "Product Saved Successfully to Database!");
            }
            
            pst.close();
            conn.close(); // Tutup sambungan
            
        } else {
            throw new Exception("Database connection failed!");
        }
        
            File file = new File("product.txt");
            BufferedWriter writer = new BufferedWriter(new FileWriter(file, true));
            
            
            writer.write(productId + "," + productName + "," + productQty + "," + productPrice);
            writer.newLine();
            writer.close();

            loadProductData(); 
            loadDeleteProduct();
            clearFields();

        
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
                                        

    
    }//GEN-LAST:event_saveActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        clearFields();

    }//GEN-LAST:event_clearActionPerformed

    private void txtproductIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtproductIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtproductIdActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        pnlRegister.setVisible(false);
         pnlUpdate.setVisible(true);
         
         int row = tblProduct.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(this,
                    "Please select a product from the table.");
            return;
        }

        try {
        // 1. Ambil data terkini daripada text field GUI korang
        String productId = txtproductId1.getText().trim();
        String productName = txtproductName1.getText().trim();
        String productQty = txtproductQty1.getText().trim();
        String productPrice = txtprice1.getText().trim();

        if (productId.isEmpty() || productName.isEmpty() || productQty.isEmpty() || productPrice.isEmpty()) {
            throw new Exception("Please fill all fields before updating!");
        }

        // 2. Sambung dan kemas kini data di MySQL Database
        java.sql.Connection conn = DBConnection.getConnection();
        if (conn != null) {
            String sql = "UPDATE products SET product_name = ?, quantity = ?, price_unit = ? WHERE product_id = ?";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            
            pst.setString(1, productName);
            pst.setInt(2, Integer.parseInt(productQty));
            pst.setInt(3, Integer.parseInt(productPrice));
            pst.setString(4, productId);
           

            int rowsUpdated = pst.executeUpdate();
            if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(this, "Product updated successfully in Database.");
            } else {
                JOptionPane.showMessageDialog(this, "Product ID not found in database.");
            }
            
            pst.close();
            conn.close();
        } else {
            throw new Exception("Database connection failed!");
        }
        
        DefaultTableModel model =
                (DefaultTableModel) tblProduct.getModel();

        model.setValueAt(txtproductId1.getText(), row, 0);
        model.setValueAt(txtproductName1.getText(), row, 1);
        model.setValueAt(txtproductQty1.getText(), row, 2);
        model.setValueAt(txtprice1.getText(), row , 3);


        saveTableToFile();


        loadProductData();
        loadViewData();
        loadDeleteProduct();
        clearFields();
        }catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Please ensure QUANTITY is a valid number!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        pnlRegister.setVisible(false);
        pnlUpdate.setVisible(false);
        pnlView.setVisible(true);
        pnlRemove.setVisible(false); 
    
        loadViewData();
        // TODO add your handling code here:
    }//GEN-LAST:event_viewActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        pnlRegister.setVisible(false);
        pnlUpdate.setVisible(false);
        pnlView.setVisible(false);
        pnlRemove.setVisible(true);  
       
        loadProductData();
        // TODO add your handling code here:
    }//GEN-LAST:event_removeActionPerformed

    private void deleteProductBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProductBtnActionPerformed

        try {

        int row = tblRemove.getSelectedRow();

        if(row == -1) {

            throw new Exception(
                    "Please select a Product.");
        }

        String productId = tblRemove.getValueAt(row, 0).toString();
        
        int confirm =
                JOptionPane.showConfirmDialog(
                        null,
                        "Are you sure you want to delete?",
                        "Confirm Delete",
                        JOptionPane.YES_NO_OPTION);

        if(confirm != JOptionPane.YES_OPTION) {
            return;
        }
        
        java.sql.Connection conn = DBConnection.getConnection();
        if (conn != null) {
            String sql = "DELETE FROM products WHERE product_id = ?";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            
            pst.setString(1, productId);

            int rowsDeleted = pst.executeUpdate();
            if (rowsDeleted > 0) {
                JOptionPane.showMessageDialog(this, "Product Deleted Successfully from Database.");
            } else {
                JOptionPane.showMessageDialog(this, "Product ID not found in database.");
            }

            pst.close();
            conn.close(); // Tutup sambungan database
        } else {
            throw new Exception("Database connection failed!");
        }

        DefaultTableModel model =
                (DefaultTableModel)
                tblRemove.getModel();

        model.removeRow(row);

        BufferedWriter writer =
                new BufferedWriter(
                        new FileWriter(
                                "product.txt"));

        for(int i = 0;
            i < model.getRowCount();
            i++) {

            writer.write(
                    model.getValueAt(i,0).toString() + "," +
                    model.getValueAt(i,1).toString() + "," +
                    model.getValueAt(i,2).toString() + "," +
                    model.getValueAt(i,3).toString() 
            );

            writer.newLine();
        }

        writer.close();



        

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                null,
                e.getMessage(),
                "Delete Error",
                JOptionPane.ERROR_MESSAGE);
    }
    
    loadProductData();
    loadViewData();
    loadDeleteProduct();
    
    }//GEN-LAST:event_deleteProductBtnActionPerformed

    private void tblRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRemoveMouseClicked

        int row = tblProduct.getSelectedRow();
        

        txtproductId1.setText(tblProduct.getValueAt(row, 0).toString());
        txtproductName1.setText(tblProduct.getValueAt(row, 1).toString());
        txtproductQty1.setText(tblProduct.getValueAt(row, 2).toString());
        txtprice1.setText(tblProduct.getValueAt(row, 3).toString());
// TODO add your handling code here:
    }//GEN-LAST:event_tblRemoveMouseClicked

    private void tblProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductMouseClicked
int row = tblProduct.getSelectedRow();


        txtproductId1.setText(tblProduct.getValueAt(row, 0).toString());
        txtproductName1.setText(tblProduct.getValueAt(row, 1).toString());
        txtproductQty1.setText(tblProduct.getValueAt(row, 2).toString());
        txtprice1.setText(tblProduct.getValueAt(row, 3).toString());
       // TODO add your handling code here:
    }//GEN-LAST:event_tblProductMouseClicked

    private void txtproductId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtproductId1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtproductId1ActionPerformed

    private void txtproductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtproductNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtproductNameActionPerformed

   
    public static void main(String args[]) {
     
        java.awt.EventQueue.invokeLater(() -> new ProductFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton clear;
    private javax.swing.JButton deleteProductBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblFormtitle;
    private javax.swing.JLabel lblFormtitle1;
    private javax.swing.JLabel lblFormtitle2;
    private javax.swing.JLabel lblFormtitle4;
    private javax.swing.JLabel menu;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlRegister;
    private javax.swing.JPanel pnlRemove;
    private javax.swing.JPanel pnlUpdate;
    private javax.swing.JPanel pnlView;
    private javax.swing.JButton register;
    private javax.swing.JButton remove;
    private javax.swing.JButton save;
    private javax.swing.JTable tblProduct;
    private javax.swing.JTable tblRemove;
    private javax.swing.JTable tblView;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtprice1;
    private javax.swing.JTextField txtproductId;
    private javax.swing.JTextField txtproductId1;
    private javax.swing.JTextField txtproductName;
    private javax.swing.JTextField txtproductName1;
    private javax.swing.JTextField txtproductQty;
    private javax.swing.JTextField txtproductQty1;
    private javax.swing.JButton update;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables
}
